### ISSUE TITLE
Teku ping gets bad score (zinken)

### ISSUE THREAD

**Issue by protolambda** [sigp/lighthouse#1754]
## Description

My lighthouse node receives ping requests from Teku nodes, and they all get bad scores, errors with broken pipes, and then disconnects.

## Version

v0.3.0

## Present Behaviour

See description, and debug logs: https://gist.github.com/protolambda/77b5f39f684413fa0b352a7f5b1504d9

## Expected Behaviour

Ping requests should be good? And if not, maybe a Teku bug. Worth investigating to stay connected to Teku peers.

## Steps to resolve

Try connect to a Teku node and check if pings are handled well.

**Comment by protolambda** [comment]
Just checked my teku node, seeing timeouts:
```
2020-10-09 16:57:19.992 | p2p-async-6          | DEBUG | tech.pegasys.teku.networking.eth2.peers.Eth2PeerManager | Eth2PeerManager      | Ping request failed for peer 16Uiu2HAkxL3NquPrkV9XWih33hcbh8JdRvrpXQ96oYvKFVWF2bbG
java.util.concurrent.CompletionException: tech.pegasys.teku.networking.eth2.rpc.core.RpcTimeouts$RpcTimeoutException: Rpc request timed out after 5 sec: Timed out waiting for initial response
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2152) ~[?:?]
        at tech.pegasys.teku.networking.eth2.rpc.core.ResponseStreamImpl.completeWithError(ResponseStreamImpl.java:79) ~[teku-networking-eth2-0.12.10-SNAPSHOT.jar:0.12.10-dev-478bec9e]
        at tech.pegasys.teku.networking.eth2.rpc.core.Eth2OutgoingRequestHandler.lambda$cancelRequest$2(Eth2OutgoingRequestHandler.java:173) ~[teku-networking-eth2-0.12.10-SNAPSHOT.jar:0.12.10-dev-478bec9e]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$always$14(SafeFuture.java:240) ~[teku-infrastructure-async-0.12.10-SNAPSHOT.jar:0.12.10-dev-478bec9e]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$finish$18(SafeFuture.java:258) ~[teku-infrastructure-async-0.12.10-SNAPSHOT.jar:0.12.10-dev-478bec9e]
        at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:946) ~[?:?]
        at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2330) ~[?:?]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.handle(SafeFuture.java:426) ~[teku-infrastructure-async-0.12.10-SNAPSHOT.jar:0.12.10-dev-478bec9e]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.finish(SafeFuture.java:253) ~[teku-infrastructure-async-0.12.10-SNAPSHOT.jar:0.12.10-dev-478bec9e]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.always(SafeFuture.java:240) ~[teku-infrastructure-async-0.12.10-SNAPSHOT.jar:0.12.10-dev-478bec9e]
        at tech.pegasys.teku.networking.eth2.rpc.core.Eth2OutgoingRequestHandler.cancelRequest(Eth2OutgoingRequestHandler.java:173) ~[teku-networking-eth2-0.12.10-SNAPSHOT.jar:0.12.10-dev-478bec9e]
        at tech.pegasys.teku.networking.eth2.rpc.core.Eth2OutgoingRequestHandler.cancelRequest(Eth2OutgoingRequestHandler.java:162) ~[teku-networking-eth2-0.12.10-SNAPSHOT.jar:0.12.10-dev-478bec9e]
        at tech.pegasys.teku.networking.eth2.rpc.core.Eth2OutgoingRequestHandler.lambda$ensureFirstBytesArriveWithinTimeLimit$3(Eth2OutgoingRequestHandler.java:183) ~[teku-networking-eth2-0.12.10-SNAPSHOT.jar:0.12.10-dev-478bec9e]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137) ~[?:?]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$2(SafeFuture.java:132) ~[teku-infrastructure-async-0.12.10-SNAPSHOT.jar:0.12.10-dev-478bec9e]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883) ~[?:?]
        at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2315) ~[?:?]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:466) ~[teku-infrastructure-async-0.12.10-SNAPSHOT.jar:0.12.10-dev-478bec9e]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:28) ~[teku-infrastructure-async-0.12.10-SNAPSHOT.jar:0.12.10-dev-478bec9e]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:127) ~[teku-infrastructure-async-0.12.10-SNAPSHOT.jar:0.12.10-dev-478bec9e]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateTo(SafeFuture.java:216) ~[teku-infrastructure-async-0.12.10-SNAPSHOT.jar:0.12.10-dev-478bec9e]
        at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119) ~[teku-infrastructure-async-0.12.10-SNAPSHOT.jar:0.12.10-dev-478bec9e]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: tech.pegasys.teku.networking.eth2.rpc.core.RpcTimeouts$RpcTimeoutException: Rpc request timed out after 5 sec: Timed out waiting for initial response
        ... 16 more
```

**Comment by protolambda** [comment]
Best guess is that Teku is not closing the write side correctly, which is required for lighthouse to respond to the Teku request (I think). And then the timeout breaks the stream, and lighthouse complains about a broken pipe.

CC @Nashatyrev

**Comment by mbaxter** [comment]
Looks like this timeout we're hitting gets set up after we close the write stream: https://github.com/PegaSysEng/teku/blob/daf3d2478dd8bbbe84ba563c247577bcdc5daf09/networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/rpc/core/Eth2OutgoingRequestHandler.java#L69-L72

**Comment by Nashatyrev** [comment]
Would be quite handy adding `--Xlog-wire-mux-enabled` option for Teku to track the issue

**Comment by AgeManning** [comment]
Hmmm we dont really log incoming failed requests as they could be spam. Might have to do some interop testing offline. I'll reach out.

**Comment by Nashatyrev** [comment]
Looks like this is the Teku side issue: after receiving `Ping` response (this is actual for any RPC response) Teku is sending stream `RESET` which is incorrect as the stream should be assumed closed when both sides send `CLOSE`. `RESET` is to be used when need to close a stream _abruptly_ and shouldn't be used in a regular exchange

**Comment by Nashatyrev** [comment]
This doesn't explain the above timeout on Teku side though it may be just a coincidence

**Comment by AgeManning** [comment]
@Nashatyrev Do we still have issues with ping after the fix?

**Comment by Nashatyrev** [comment]
@AgeManning just double-checked and merged https://github.com/PegaSysEng/teku/pull/3001. We don't send `RESET` anymore 
I believe this issue can be closed now
