### ISSUE TITLE
error when launched from script

### ISSUE THREAD

**Issue by jupiter126** [sigp/lighthouse#1991]
## Description
I did a quick update script so lighthouse remains up to date, lighthouse --version works but gives an error:

thread 'main' panicked at 'Error writing Error to stdout: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/errors.rs:401:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

## Version

1.0.0 and 1.0.1

## Present Behaviour
output of script with export RUST_BACKTRACE=full

root@eth:~# ./upgrade_lighthouse.sh    
0
1
2
up to date (v1.0.1 = v1.0.1 )
root@eth:~# ./upgrade_lighthouse.sh 
0
1
2
up to date (v1.0.1 = v1.0.1 )
root@eth:~# ./upgrade_lighthouse.sh 
0
thread 'main' panicked at 'Error writing Error to stdout: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/errors.rs:401:55
stack backtrace:
   0:     0x55e2f47fb840 - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x55e2f47fb840 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x55e2f47fb840 - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:     0x55e2f47fb840 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:     0x55e2f48203cc - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:     0x55e2f47f2572 - std::io::Write::write_fmt::haeeb374d93a67eac
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:     0x55e2f47fe00d - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:     0x55e2f47fe00d - std::sys_common::backtrace::print::h301abac8bb2e3e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:     0x55e2f47fe00d - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:     0x55e2f47fdcb8 - std::panicking::default_hook::h9b1a691049a0ec8f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:     0x55e2f47fe6f1 - std::panicking::rust_panic_with_hook::h2bdec87b60580584
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:     0x55e2f47fe299 - std::panicking::begin_panic_handler::{{closure}}::h101ca09d9df5db47
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:     0x55e2f47fbcac - std::sys_common::backtrace::__rust_end_short_backtrace::h3bb85654c20113ca
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:     0x55e2f47fe259 - rust_begin_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:     0x55e2f481dfc1 - core::panicking::panic_fmt::h48c31e1e3d550146
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
  15:     0x55e2f481dde3 - core::option::expect_none_failed::h6154dc750ae47ade
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
  16:     0x55e2f47c526a - core::result::Result<T,E>::expect::hb8e9f4ca0dfd10c6
  17:     0x55e2f47c790e - clap::errors::Error::exit::h461c17a27a008ee8
  18:     0x55e2f47acf1e - clap::app::App::get_matches_from::{{closure}}::ha5b8e0cd19ea5977
  19:     0x55e2f47acca9 - clap::app::App::get_matches::h9785f996fe45732b
  20:     0x55e2f31491bf - lighthouse::main::hfc2165d50efa0d27
  21:     0x55e2f2bed5a3 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha251ca927d50258a
  22:     0x55e2f2bef719 - std::rt::lang_start::{{closure}}::h2c4cc5af0df1d705
  23:     0x55e2f47fec07 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::he179d32a5d10d957
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:259
  24:     0x55e2f47fec07 - std::panicking::try::do_call::hcb3d5e7be089b2b4
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:381
  25:     0x55e2f47fec07 - std::panicking::try::h7ac93b0cd56fb701
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:345
  26:     0x55e2f47fec07 - std::panic::catch_unwind::h7b40e396c93a4fcd
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:382
  27:     0x55e2f47fec07 - std::rt::lang_start_internal::h142b9cc66267fea1
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:51
  28:     0x55e2f314f502 - main
  29:     0x7f39d74cc0b3 - __libc_start_main
  30:     0x55e2f2a33b69 - _start
  31:                0x0 - <unknown>
1
2
up to date (v1.0.1 = v1.0.1 )

## Expected Behaviour

main should not panic

## Steps to resolve

The script works (returns version), but I don't know why the panic.  don't know how to solve or even if it is important, but I prefer reporting issue just in case!
note: system is ubuntu 20.04 on a VPS
calling code with culprit line in bold
cat upgrade_lighthouse.sh

export RUST_BACKTRACE=full
echo 0
**currentver="$(/usr/local/bin/lighthouse --version|head -n1|cut -f 2 -d' '|cut -f1 -d'-')"**
echo 1
latestver=$(curl -s https://github.com/sigp/lighthouse/releases/latest|cut -f2 -d'"'|rev|cut -f1 -d'/'|rev)
echo 2

if [[ "$currentver" != "$latestver" ]]; then
        echo "requires update ($currentver != $latestver )"
        wget -q "https://github.com/sigp/lighthouse/releases/download/$latestver/lighthouse-$latestver-x86_64-unknown-linux-gnu.tar.gz"
        tar -xzf "lighthouse-$latestver-x86_64-unknown-linux-gnu.tar.gz"
        systemctl stop lighthousebeacon lighthousevalidator && sleep 2 && chown root:root lighthouse && chmod 755 lighthouse && mv lighthouse /usr/local/bin/
        rm "lighthouse-$latestver-x86_64-unknown-linux-gnu.tar.gz"
        systemctl start lighthousebeacon lighthousevalidator
else
        echo "up to date ($currentver = $latestver )"
fi

**Comment by jupiter126** [comment]
seems mostly fixed in 1.0.2.  
My script issues a warning 1 on 20 runs now instead of 1 panic 9 out of 10 runs. was probably a race condition somewhere
