### ISSUE TITLE
<jemalloc>: arena 0 background thread creation failed (1)

### ISSUE THREAD

**Issue by ibadullaev-inc4** [sigp/lighthouse#4045]
Hi when I execute following command, I receive output.
Does this mean my CPU is incompatible ? 

```
root@hz8 ~/home# docker run -it sigp/lighthouse lighthouse -V
<jemalloc>: arena 0 background thread creation failed (1)
Lighthouse v3.5.0-0fb58a6
```

CPU Info:

```
Vendor ID:           GenuineIntel
CPU family:          6
Model:               158
Model name:          Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz

```

**Comment by michaelsproul** [comment]
Hmm, haven't seen that before.

What version of Docker are you using? `docker --version` should print some info.

Similarly the Linux kernel version could be good to know: `uname -a`.

Does Lighthouse run when you run commands other than the version command?

If not, as a workaround you could build the image from source, which will turn off jemalloc. See: https://lighthouse-book.sigmaprime.io/docker.html#building-the-docker-image

**Comment by ibadullaev-inc4** [comment]
>>> What version of Docker are you using? docker --version should print some info.


```
root@hz8 ~/home # docker --version
Docker version 18.09.1, build 4c52b90
```

>>> Similarly the Linux kernel version could be good to know: uname -a.


```
root@hz8 ~/home # uname -a
Linux hz8 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux
```

>>> Os info

```
root@hz8 ~/home # cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

```


>>> Does Lighthouse run when you run commands other than the version command?
>>> When I try to start beacon 

```
root@hz8 ~/ethValidator # docker logs ethvalidator_beacon_node_1
<jemalloc>: arena 0 background thread creation failed (1)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', /cargo/registry/src/github.com-1ecc6299db9ec823/slog-async-2.7.0/lib.rs:303:14
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: slog_async::AsyncBuilder<D>::build
   4: environment::EnvironmentBuilder<E>::initialize_logger
   5: lighthouse::main::{{closure}}
   6: lighthouse::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
<jemalloc>: arena 0 background thread creation failed (1)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', /cargo/registry/src/github.com-1ecc6299db9ec823/slog-async-2.7.0/lib.rs:303:14
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: slog_async::AsyncBuilder<D>::build
   4: environment::EnvironmentBuilder<E>::initialize_logger
   5: lighthouse::main::{{closure}}
   6: lighthouse::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
<jemalloc>: arena 0 background thread creation failed (1)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', /cargo/registry/src/github.com-1ecc6299db9ec823/slog-async-2.7.0/lib.rs:303:14
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: slog_async::AsyncBuilder<D>::build
   4: environment::EnvironmentBuilder<E>::initialize_logger
   5: lighthouse::main::{{closure}}
   6: lighthouse::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
<jemalloc>: arena 0 background thread creation failed (1)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', /cargo/registry/src/github.com-1ecc6299db9ec823/slog-async-2.7.0/lib.rs:303:14
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: slog_async::AsyncBuilder<D>::build
   4: environment::EnvironmentBuilder<E>::initialize_logger
   5: lighthouse::main::{{closure}}
   6: lighthouse::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
<jemalloc>: arena 0 background thread creation failed (1)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', /cargo/registry/src/github.com-1ecc6299db9ec823/slog-async-2.7.0/lib.rs:303:14
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: slog_async::AsyncBuilder<D>::build
   4: environment::EnvironmentBuilder<E>::initialize_logger
   5: lighthouse::main::{{closure}}
   6: lighthouse::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
<jemalloc>: arena 0 background thread creation failed (1)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', /cargo/registry/src/github.com-1ecc6299db9ec823/slog-async-2.7.0/lib.rs:303:14
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: slog_async::AsyncBuilder<D>::build
   4: environment::EnvironmentBuilder<E>::initialize_logger
   5: lighthouse::main::{{closure}}
   6: lighthouse::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
<jemalloc>: arena 0 background thread creation failed (1)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', /cargo/registry/src/github.com-1ecc6299db9ec823/slog-async-2.7.0/lib.rs:303:14
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: slog_async::AsyncBuilder<D>::build
   4: environment::EnvironmentBuilder<E>::initialize_logger
   5: lighthouse::main::{{closure}}
   6: lighthouse::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
<jemalloc>: arena 0 background thread creation failed (1)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', /cargo/registry/src/github.com-1ecc6299db9ec823/slog-async-2.7.0/lib.rs:303:14
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: slog_async::AsyncBuilder<D>::build
   4: environment::EnvironmentBuilder<E>::initialize_logger
   5: lighthouse::main::{{closure}}
   6: lighthouse::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
<jemalloc>: arena 0 background thread creation failed (1)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', /cargo/registry/src/github.com-1ecc6299db9ec823/slog-async-2.7.0/lib.rs:303:14
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: slog_async::AsyncBuilder<D>::build
   4: environment::EnvironmentBuilder<E>::initialize_logger
   5: lighthouse::main::{{closure}}
   6: lighthouse::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
<jemalloc>: arena 0 background thread creation failed (1)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', /cargo/registry/src/github.com-1ecc6299db9ec823/slog-async-2.7.0/lib.rs:303:14
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: slog_async::AsyncBuilder<D>::build
   4: environment::EnvironmentBuilder<E>::initialize_logger
   5: lighthouse::main::{{closure}}
   6: lighthouse::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
<jemalloc>: arena 0 background thread creation failed (1)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', /cargo/registry/src/github.com-1ecc6299db9ec823/slog-async-2.7.0/lib.rs:303:14
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: slog_async::AsyncBuilder<D>::build
   4: environment::EnvironmentBuilder<E>::initialize_logger
   5: lighthouse::main::{{closure}}
   6: lighthouse::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
<jemalloc>: arena 0 background thread creation failed (1)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', /cargo/registry/src/github.com-1ecc6299db9ec823/slog-async-2.7.0/lib.rs:303:14
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: slog_async::AsyncBuilder<D>::build
   4: environment::EnvironmentBuilder<E>::initialize_logger
   5: lighthouse::main::{{closure}}
   6: lighthouse::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
<jemalloc>: arena 0 background thread creation failed (1)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', /cargo/registry/src/github.com-1ecc6299db9ec823/slog-async-2.7.0/lib.rs:303:14
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: slog_async::AsyncBuilder<D>::build
   4: environment::EnvironmentBuilder<E>::initialize_logger
   5: lighthouse::main::{{closure}}
   6: lighthouse::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
<jemalloc>: arena 0 background thread creation failed (1)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', /cargo/registry/src/github.com-1ecc6299db9ec823/slog-async-2.7.0/lib.rs:303:14
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: slog_async::AsyncBuilder<D>::build
   4: environment::EnvironmentBuilder<E>::initialize_logger
   5: lighthouse::main::{{closure}}
   6: lighthouse::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
<jemalloc>: arena 0 background thread creation failed (1)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', /cargo/registry/src/github.com-1ecc6299db9ec823/slog-async-2.7.0/lib.rs:303:14
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: slog_async::AsyncBuilder<D>::build
   4: environment::EnvironmentBuilder<E>::initialize_logger
   5: lighthouse::main::{{closure}}
   6: lighthouse::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
<jemalloc>: arena 0 background thread creation failed (1)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', /cargo/registry/src/github.com-1ecc6299db9ec823/slog-async-2.7.0/lib.rs:303:14
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: slog_async::AsyncBuilder<D>::build
   4: environment::EnvironmentBuilder<E>::initialize_logger
   5: lighthouse::main::{{closure}}
   6: lighthouse::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
<jemalloc>: arena 0 background thread creation failed (1)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', /cargo/registry/src/github.com-1ecc6299db9ec823/slog-async-2.7.0/lib.rs:303:14
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: slog_async::AsyncBuilder<D>::build
   4: environment::EnvironmentBuilder<E>::initialize_logger
   5: lighthouse::main::{{closure}}
   6: lighthouse::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by michaelsproul** [comment]
I think the permissions error is unrelated, if you fix that it might run. Try running `sigp/lighthouse:v3.4.0` (which doesn't use jemalloc) and you'll get the same thing. You need to make sure that the Lighthouse datadir is writable by the user running the Lighthouse process. The default datadir is `~/.lighthouse/{network}`. For Docker it will be the permissions on the volume you're mounting

**Comment by ibadullaev-inc4** [comment]
But this error I received also when I did't mount volume into container

root@hz8 ~/ethValidator # docker run -it sigp/lighthouse:v3.4.0 lighthouse beacon_node --http --network prater


thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', /cargo/registry/src/github.com-1ecc6299db9ec823/slog-async-2.7.0/lib.rs:303:14
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
   2: core::result::unwrap_failed
             at ./rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/result.rs:1791:5
   3: slog_async::AsyncBuilder<D>::build
   4: environment::EnvironmentBuilder<E>::initialize_logger
   5: lighthouse::main::{{closure}}
   6: lighthouse::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by michaelsproul** [comment]
@ibadullaev-inc4 I think your Docker setup might be messed up. When no volumes are mounted Docker should be writing to the container's overlayfs, which is represented as a file in `/var/lib/docker` (see [docs](https://docs.docker.com/storage/storagedriver/overlayfs-driver/#how-the-overlay2-driver-works)). Maybe the permissions on that directory are read-only?

You could also try updating your Docker engine to a newer version, in my experience the versions bundled with distros are often lacking features expected by newer images and scripts. There are packages for Debian [here](https://docs.docker.com/engine/install/debian/).

**Comment by ibadullaev-inc4** [comment]
The permissions of dir /var/lib/docker - look like normal.
But you are right, this behavior not related lighthouse, I do not know what exactly wrong, but after change the VM to another one, this issue resolved. 

Thanks a lot.
