### ISSUE TITLE
shapeshift error

### ISSUE THREAD

**Issue by satoshi2K** [sigp/lighthouse#6058]
I ran into a problem using the developers section of ShapeShift/KeepKey

Cannot read properties of null (reading 'target')
```
Channel: DevTools
Initial URL: https://private.shapeshift.com/#/trade
Chrome Version: 108.0.5359.62
Stack Trace: TypeError: Cannot read properties of null (reading 'target')
    at Driver$3.connect (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:1205:417)
    at snapshotGather$2 (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:1220:10)
    at snapshot (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:1229:759)
    at i (devtools://devtools/bundled/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%408ddd17179797b1f6a8232c8d1770efd6c123abf6%2F:1:2376)
    at async self.onmessage (devtools://devtools/bundled/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%408ddd17179797b1f6a8232c8d1770efd6c123abf6%2F:1:2975)
```

Please notify me if this doesn't belong here.

**Comment by michaelsproul** [comment]
That must be a different Lighthouse, we do not have any JS code that would be used by ShapeShift
